<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	  $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
	  $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();
	  $message = $objectManager->get('\Magento\Framework\View\Element\Messages');
	  //print_r($message);
	  ?>

<div id="login-form-content" class="modal hide fade in" style="display:none;">
			<div class="modal-header login-header contact-header">
				 <a class="logo" href="<?php echo $block->getUrl(''); ?>" title="<?php /* @escapeNotVerified */ echo $storeName ?>">
				  <img src="<?php /* @escapeNotVerified */ echo $block->getLogoSrc() ?>"
             alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"
             <?php echo $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
             <?php echo $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
        /></a>
				<a class="close" data-dismiss="modal">×</a>
			</div>
			<div class="modal-body">
	
		
    <div class="row">
        <form name="page-pass" id="page-pass" method="post" action="<?php echo $storeManager->getStore()->getBaseUrl(); ?>partnerlogin/authentication/result">
			
			<fieldset class="fieldset">
			<div class="form-head" style='font-family: "RobotoSlab-Bold";font-weight: bold;color: #003e7e;font-size: 26px;'><span><?php /* @escapeNotVerified */ echo __('School Partner Login') ?></span></div><br>
			<p id="sclpartnermsg" style="display:none;border: 1px solid #DF2700; padding: 5px; background-color: #FF5733; color: white;font-weight:bold; border-radius: 4px;"></p>
			<!--<div class="form-group">
					<label for="Page" class="label" style="float: left;font-size: 14px;">
						<span><?php /* @escapeNotVerified */ echo __('Select School') ?></span>
					</label>

				  <br/>
				<div class="control">
						<select id="pageid" name="pageid" class="required-entry">
						  <option value="">Select Your School</option>
						  <option value="69">Westwood</option>
						  <option value="70">Philips</option>
						  <option value="72">Roxbury Latin</option>
						  <option value="82">Natick</option>
					</select>
				</div>
			</div>-->
			<div class="form-group">
				<label for="Page" class="label" style="float: left;font-size: 14px;">
					<span><?php /* @escapeNotVerified */ echo __('School Password') ?></span>
				</label>
				<div class="control">
					<input type="password" id="password" 
						   name="password"
						   class="input-text required-entry">
						   <input type="hidden" id="status" 
						   name="status" value="1"
						   class="input-text">
				</div>
			</div>
			<!--<div class="form-group">
				<div class="actions-toolbar">
					<div class="primary">
						<button type="submit" class="btn btn-success" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>">
							<span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
						</button>
					</div>
				</div>
			</div>-->
			<div class="form-group foot-action">
				<div class="actions-toolbar">
					<div class="primary">
						<input class="btn btn-success" type="submit" form="page-pass" value="Submit" id="submit">
						<a href="#" class="btn cancel" data-dismiss="modal">Cancel</a>
					</div>
				</div>
			</div>
		</fieldset>
        </form>
    </div>

			</div>
			
		</div>
<div class="login-loading modal-backdrop fade in"  style="display:none;"><img src="<?php echo $block->getViewFileUrl('images/ajax-loader.gif')?>" alt="Loading..."></div>
<script type="text/javascript">
	require(['jquery'],function($){		
		var form = $('#page-pass');		
		$('#sclpartnermsg').hide();
		form.submit(function (ev) {
			console.log(ev);
			$(".login-loading").css({"display": "block"});   
			$.ajax({
				type: "POST",
				url:  "<?php echo $storeManager->getStore()->getBaseUrl(); ?>partnerlogin/authentication/result", 
				data: $("#page-pass").serialize(),
				success: function(result){
					$('.login-loading').hide();
					if(result=='Password Mismatch'){
						$('#sclpartnermsg').html(result);
						$('#sclpartnermsg').show();
					} else {
						window.location.href =result;
					}
				}
			});
			ev.preventDefault();
		});
	});
</script>
<script type="text/javascript">
require([
    'jquery',
    'mage/mage'
], function($){

   var dataForm = $('#page-pass');
   dataForm.mage('validation', {});
   
   $('.partner-login,#login-form-content .modal-header .close,#login-form-content .foot-action .cancel').click(function () {
        $("#login-form-content")
            .css('opacity', 0)
            .slideToggle('slow')
            .animate(
                { opacity: 1 },
                { queue: false, duration: 'slow' }
            );
     });

});
</script>
