<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	  $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
	  $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();
	   $session = $objectManager->get('Magento\Customer\Model\Session');
			 $message=$session->getpagemessage();
	  ?>
<div class="row">
<div class="col-md-6 col-sm-12">
	<?php if($message){echo $message;}?>
<form class="form" action="<?php echo $storeManager->getStore()->getBaseUrl(); ?>partnerlogin/authentication/result" method="post" name="page-pass1" id="page-pass1">

		<fieldset class="fieldset">
			<div class="form-head" style='font-family: "RobotoSlab-Bold";font-weight: bold;color: #003e7e;font-size: 26px;'><span><?php /* @escapeNotVerified */ echo __('School Partner Login') ?></span></div><br>
			
			<div class="form-group">
				<label for="Page" class="label" style="float: left;font-size: 14px;">
					<span><?php /* @escapeNotVerified */ echo __('School Password') ?></span>
				</label>
				<div class="control">
					<input type="password" id="password" 
						   name="password"
						   class="input-text required-entry">
				</div>
			</div>
			<div class="form-group">
				<div class="actions-toolbar">
					<div class="primary">
						<button type="submit" class="btn btn-success" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>">
							<span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
						</button>
					</div>
				</div>
			</div>
		</fieldset>
</form>
</div>
</div>
<script type="text/javascript">
require([
    'jquery',
    'mage/mage'
], function($){
$( "form#page-pass1" ).append($(".page.messages");
   var dataForm = $('#page-pass');
   dataForm.mage('validation', {});

});
</script>

